---
internal_reverse_proxy_records:
  - domain: portainer.{{ domain_name }}
    upstream: "https://mediacenter.tailb3a7a.ts.net:9443"
    tls_skip_verify: true
  - domain: pve.{{ domain_name }}
    upstream: "https://pve.tailb3a7a.ts.net:8006"
    tls_skip_verify: true
  - domain: ui.{{ domain_name }}
    upstream: "https://{{ unifi_console_ip }}:443"
    tls_skip_verify: true
  - domain: qbittorrent.{{ domain_name }}
    upstream: "http://mediacenter.tailb3a7a.ts.net:8585"
  - domain: radarr.{{ domain_name }}
    upstream: "http://mediacenter.tailb3a7a.ts.net:7878"
  - domain: sonarr.{{ domain_name }}
    upstream: "http://mediacenter.tailb3a7a.ts.net:8989"
  - domain: prowlarr.{{ domain_name }}
    upstream: "http://mediacenter.tailb3a7a.ts.net:9696"
  - domain: profilarr.{{ domain_name }}
    upstream: "http://mediacenter.tailb3a7a.ts.net:6868"
  - domain: flaresolverr.{{ domain_name }}
    upstream: "http://mediacenter.tailb3a7a.ts.net:8191"
  - domain: trmnl.{{ domain_name }}
    upstream: "http://mediacenter.tailb3a7a.ts.net:2300"

external_reverse_proxy_records:
  - domain: jellyfin.{{ domain_name }}
    upstream: "http://mediacenter.tailb3a7a.ts.net:8096"
  - domain: keep.{{ domain_name }}
    upstream: "http://vps.tailb3a7a.ts.net:9721"
  - domain: seerr.{{ domain_name }}
    upstream: "http://mediacenter.tailb3a7a.ts.net:5055"
...
