---
all:
  children:
    servers:
      hosts:
        pve:
        rpi:
        vps:
    vms:
      hosts:
        mediacenter:
    docker_hosts:
      hosts:
        mediacenter:
        rpi:
        vps:
    portainer_server:
      hosts:
        mediacenter:
    portainer_agents:
      hosts:
        rpi:
        vps:
...
