---
- name: Deploy Portainer server
  hosts: portainer_server
  gather_facts: false
  tasks:
    - name: Portainer server container
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ee:2.43.0
        restart_policy: unless-stopped
        command:
          - "--trusted-origins=https://portainer.{{ domain_name }},https://{{ ansible_host }}:9443"
        published_ports:
          - 9443:9443
          - 8000:8000
        volumes:
          - portainer_data:/data
          - /var/run/docker.sock:/var/run/docker.sock

- name: Deploy Portainer agents
  hosts: portainer_agents
  gather_facts: false
  tasks:
    - name: Portainer agent container
      community.docker.docker_container:
        name: portainer_agent
        image: portainer/agent:2.43.0
        restart_policy: unless-stopped
        published_ports:
          - 9001:9001
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volumes:/var/lib/docker/volumes
...
