name: Ansible Apply

on:
  push:
    branches:
      - main
    paths:
      - ansible/**
      - ansible.cfg

concurrency:
  group: ansible-apply
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v7

      - id: select
        uses: ./.github/actions/ansible-select

      - uses: ./.github/actions/ansible-setup
        with:
          ts-oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          ts-oauth-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}

      - name: Ansible apply
        if: steps.select.outputs.list != ''
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          BASE_DOMAIN: ${{ secrets.BASE_DOMAIN }}
          UNIFI_CONSOLE_IP: ${{ secrets.UNIFI_CONSOLE_IP }}
        run: |
          ansible-playbook -i ansible/inventory/hosts.yaml ${{ steps.select.outputs.list }} \
            --extra-vars "domain_name=$BASE_DOMAIN unifi_console_ip=$UNIFI_CONSOLE_IP"
